name: petapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  flutter_svg_provider: ^1.0.3
  get: 4.6.5
  intl: ^0.17.0
  pinput: ^2.2.12
  google_fonts: ^3.0.1
  easy_popup: ^1.0.0
  rflutter_alert: ^1.0.3
  dotted_line: ^3.1.0
  http: ^0.13.5
  dio: ^4.0.4
  path_provider: ^2.0.8
  cached_network_image: ^3.2.2
  flutter_launcher_icons: ^0.10.0
  dropdown_button2: ^1.9.2
  image_picker: ^0.8.6
  
  flutter_barcode_scanner: ^2.0.0
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.5
  fluttertoast: ^8.0.9
  get_storage: ^2.0.3
  file_picker: 5.2.0+1 
  future_progress_dialog: ^0.2.0
 
  url_launcher: ^6.1.6
  email_validator: ^2.1.17
  flutter_local_notifications: ^12.0.3
  timezone: ^0.9.0
  flutter_app_badger: ^1.5.0
  badges: ^2.0.3
  top_snackbar_flutter: ^2.1.1
  onesignal_flutter: ^3.4.2
  connectivity: ^3.0.6
  firebase_core: ^1.10.6
  cloud_firestore: ^2.5.0
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.6.6
  flutter_downloader: ^1.9.0
  
  device_info_plus: ^8.0.0
  downloads_path_provider_28: ^0.1.2

 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Home/logo.png"  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
   
    - assets/Home/
  uses-material-design: true
